### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by wj1106** [pdimens/LepWrap#12]
Hello,
I have an F1 cross with 250 progeny individuals and ~2.1million markers. Using LepMap3 which is a wonderful tool to build a genetic linkage map, everything went well until I got a java error with OrderMarkers2. 
Here is my code:
java -cp LepWrap/software/LepMap3 OrderMarkers2 map=map52_subset10_lod10JS_iterate1.txt data=test.call chromosome=1 numThreads=100 sexAveraged=1 >map52_subset10_lod10JS_iterate1_chr1.txt 2>map52_subset10_lod10JS_iterate1_chr1.log
I got this error:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at OrderFinder$SingleFamily.<init>(OrderFinder.java:658)
        at OrderFinder.setHaplotypes(OrderFinder.java:463)
        at Order.orderChromosome(Order.java:561)
        at Order.orderChromosomes(Order.java:445)
        at OrderMarkers2.main(OrderMarkers2.java:171)
Then I change the code:
java -Xmx 512m -cp LepWrap/software/LepMap3 OrderMarkers2 map=map52_subset10_lod10JS_iterate1.txt data=test.call chromosome=1 numThreads=64 sexAveraged=1 >map52_subset10_lod10JS_iterate1_chr1.txt 2>map52_subset10_lod10JS_iterate1_chr1.2.log
I got anther error:
Invalid maximum heap size: -Xmx
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
I have no idea to solve it. Could you please help me resolve this issue?
Thanks so much!

Sincerely,
Jie

**Comment by wj1106** [comment]
Hello, problem solved, I made a stupid mistake as there is no blank in"-Xmx 512m" .Sorry to bother you, have a nice day!
